fita = 'AGCCGCCAACTGGCTGGTCTACGCCTGCGATATGTGATGATCCGCTGGTGTAATAACTTTTGCCGTCTGTTACTTCTAGTTGTATTTTAACATTCAGTCTAGAGGCCTAATCCTCCCATACCGTTCCCCAGCACTACTGGCAGTCTTGGACCCATGACGGGGTGAACTAAGTGCCCCTTTATTCAGGATAACTGGGCATTAGTGGGGACATGATGCGTTCTGTGTACGATCTGTCGCGCACAGCGTACGCGCCTAGCTCATGGTAAGTGCTTGGTCTCTATATACGGTTCAATTGTGAGGCACTATTTAGCAAGTATTGCAAGGTAAATGTGCGCAGGCGTGGAATTTTTTCACGGCCGCGTATCGTACCGGCGGGACTGACGCTAGCACAAAACGCCGGTGATAGTCTCGCCGCGAAAGCGGTAGGGCACTGTTGGTAAAATCCAAGGAGTGACATGCTTAAATGTTCCATTAACGAAGAAAGAAATGGCCCATTACAGCACGTTAAGTATCACTCCATAATATCGTGGGACTTAGAAAATTTGTCAACTGGCCGACATTGAGACAGGTATGCGCGCGATCAACAATGAACACGGAGGGTGGAATCCAGTGGTGTTACGATTTAACATTCTACGGGAGTCCGTATACATGGTAATGGTGCAAAACATCCCGTGGGATAGAATTTGGGGCTCTTGAGATAACGGCGAAGCACATCAAGAACACTTGATTTACCTGCGCGGCGTGTAATGCCTTTCAGCACCCGCCGGTTCCGTCTTTGCAGCCGCCAGGAGGGGAATAGAGACTTGAGACTCCTGACGGCAGGACA'
A = 0
C = 0
T = 0
G = 0

for molecula in fita:
  if molecula == 'A':
    A += 1
  elif molecula == 'C':
    C += 1
  elif molecula == 'G':
    G += 1
  elif molecula == 'T':
    T += 1

print(A, C, G, T)